        LoadBool(root, "Visuals","Enabled", g::visualsEnabled);
        LoadBool(root, "Visuals","Box", g::visualsBox);
        LoadBool(root, "Visuals","Health", g::visualsHealth);
        LoadBool(root, "Visuals","HealthText", g::visualsHealthText);
        LoadBool(root, "Visuals","Armor", g::visualsArmor);
        LoadBool(root, "Visuals","ArmorText", g::visualsArmorText);
        LoadBool(root, "Visuals","Name", g::visualsName);
        LoadFloat(root, "Visuals","NameFontSize", g::visualsNameFontSize);
        LoadBool(root, "Visuals","Weapon", g::visualsWeapon);
        LoadBool(root, "Visuals","WeaponText", g::visualsWeaponText);
        LoadFloat(root, "Visuals","WeaponTextSize", g::visualsWeaponTextSize);
        LoadColor(root, "Visuals","WeaponTextColor", g::visualsWeaponTextColor);
        LoadBool(root, "Visuals","WeaponIcon", g::visualsWeaponIcon);
        LoadBool(root, "Visuals","WeaponIconNoKnife", g::visualsWeaponIconNoKnife);
        LoadFloat(root, "Visuals","WeaponIconSize", g::visualsWeaponIconSize);
        LoadColor(root, "Visuals","WeaponIconColor", g::visualsWeaponIconColor);
        LoadBool(root, "Visuals","WeaponAmmo", g::visualsWeaponAmmo);
        LoadFloat(root, "Visuals","WeaponAmmoSize", g::visualsWeaponAmmoSize);
        LoadColor(root, "Visuals","WeaponAmmoColor", g::visualsWeaponAmmoColor);
        LoadBool(root, "Visuals","Distance", g::visualsDistance);
        LoadFloat(root, "Visuals","DistanceSize", g::visualsDistanceSize);
        LoadBool(root, "Visuals","Skeleton", g::visualsSkeleton);
        LoadBool(root, "Visuals","SkeletonDots", g::visualsSkeletonDots);
        LoadBool(root, "Visuals","Snaplines", g::visualsSnaplines);
        LoadBool(root, "Visuals","SnapFromTop", g::visualsSnaplineFromTop);
        LoadBool(root, "Visuals","VisibilityColoring", g::visualsVisibilityColoring);
        LoadBool(root, "Visuals","VisibleOnly", g::visualsVisibleOnly);
        LoadBool(root, "Visuals","ShowTeammates", g::visualsShowTeammates);
        LoadBool(root, "Visuals","OffscreenArrows", g::visualsOffscreenArrows);
        LoadBool(root, "Visuals","Sound", g::visualsSound);
        LoadBool(root, "Visuals","SoundFootsteps", g::visualsSoundFootsteps);
        LoadBool(root, "Visuals","SoundShots", g::visualsSoundShots);
        LoadBool(root, "Visuals","SoundReloads", g::visualsSoundReloads);
        LoadFloat(root, "Visuals","SoundRange", g::visualsSoundRange);
        LoadFloat(root, "Visuals","SoundDuration", g::visualsSoundDuration);
        LoadBool(root, "Visuals","Flags", g::visualsFlags);
        LoadBool(root, "Visuals","Item", g::visualsItem);
        LoadBool(root, "Visuals","FlagBlind", g::visualsFlagBlind);
        LoadColor(root, "Visuals","FlagBlindColor", g::visualsFlagBlindColor);
        LoadFloat(root, "Visuals","FlagBlindSize", g::visualsFlagBlindSize);
        LoadBool(root, "Visuals","FlagScoped", g::visualsFlagScoped);
        LoadColor(root, "Visuals","FlagScopedColor", g::visualsFlagScopedColor);
        LoadFloat(root, "Visuals","FlagScopedSize", g::visualsFlagScopedSize);
        LoadBool(root, "Visuals","FlagDefusing", g::visualsFlagDefusing);
        LoadColor(root, "Visuals","FlagDefusingColor", g::visualsFlagDefusingColor);
        LoadFloat(root, "Visuals","FlagDefusingSize", g::visualsFlagDefusingSize);
        LoadBool(root, "Visuals","FlagKit", g::visualsFlagKit);
        LoadColor(root, "Visuals","FlagKitColor", g::visualsFlagKitColor);
        LoadFloat(root, "Visuals","FlagKitSize", g::visualsFlagKitSize);
        LoadBool(root, "Visuals","FlagMoney", g::visualsFlagMoney);
        LoadColor(root, "Visuals","FlagMoneyColor", g::visualsFlagMoneyColor);
        LoadFloat(root, "Visuals","FlagMoneySize", g::visualsFlagMoneySize);
        LoadBool(root, "Visuals","World", g::visualsWorld);
        LoadBool(root, "Visuals","WorldProjectiles", g::visualsWorldProjectiles);
        LoadBool(root, "Visuals","WorldSmokeTimer", g::visualsWorldSmokeTimer);
        LoadBool(root, "Visuals","WorldInfernoTimer", g::visualsWorldInfernoTimer);
        LoadBool(root, "Visuals","WorldDecoyTimer", g::visualsWorldDecoyTimer);
        LoadBool(root, "Visuals","WorldExplosiveTimer", g::visualsWorldExplosiveTimer);
        LoadBool(root, "Visuals","BombInfo", g::visualsBombInfo);
        LoadBool(root, "Visuals","BombText", g::visualsBombText);
        LoadBool(root, "Visuals","BombTime", g::visualsBombTime);
        LoadFloat(root, "Visuals","BombTextSize", g::visualsBombTextSize);
        LoadFloat(root, "Visuals","BombTimerX", g::visualsBombTimerX);
        LoadFloat(root, "Visuals","BombTimerY", g::visualsBombTimerY);
        LoadDisabledItemIds(root, "Visuals","ItemHiddenIds", g::visualsItemEnabledMask);
        LoadFloat(root, "Visuals","OffscreenSize", g::visualsOffscreenSize);
        LoadColor(root, "Visuals","BoxColor", g::visualsBoxColor);
        LoadColor(root, "Visuals","HealthColor", g::visualsHealthColor);
        LoadColor(root, "Visuals","VisibleColor", g::visualsVisibleColor);
        LoadColor(root, "Visuals","HiddenColor", g::visualsHiddenColor);
        LoadColor(root, "Visuals","ArmorColor", g::visualsArmorColor);
        LoadColor(root, "Visuals","NameColor", g::visualsNameColor);
        LoadColor(root, "Visuals","DistanceColor", g::visualsDistanceColor);
        LoadColor(root, "Visuals","SkeletonColor", g::visualsSkeletonColor);
        LoadColor(root, "Visuals","SnaplineColor", g::visualsSnaplineColor);
        LoadColor(root, "Visuals","OffscreenColor", g::visualsOffscreenColor);
        LoadColor(root, "Visuals","FlagColor", g::visualsFlagColor);
        LoadColor(root, "Visuals","WorldColor", g::visualsWorldColor);
        LoadColor(root, "Visuals","BombColor", g::visualsBombColor);
        LoadColor(root, "Visuals","SoundColor", g::visualsSoundColor);
        LoadFloat(root, "Visuals","Thickness", g::visualsThickness);

        LoadBool(root, "Radar", "Enabled", g::radarEnabled);
        LoadInt(root, "Radar", "Mode", g::radarMode);
        LoadBool(root, "Radar", "ShowLocalDot", g::radarShowLocalDot);
        LoadBool(root, "Radar", "ShowAngles", g::radarShowAngles);
        LoadBool(root, "Radar", "ShowCrosshair", g::radarShowCrosshair);
        LoadBool(root, "Radar", "ShowBomb", g::radarShowBomb);
        LoadFloat(root, "Radar", "Size", g::radarSize);
        LoadFloat(root, "Radar", "DotSize", g::radarDotSize);
        LoadFloat(root, "Radar", "WorldRotationDeg", g::radarWorldRotationDeg);
        LoadFloat(root, "Radar", "WorldScale", g::radarWorldScale);
        LoadFloat(root, "Radar", "WorldOffsetX", g::radarWorldOffsetX);
        LoadFloat(root, "Radar", "WorldOffsetY", g::radarWorldOffsetY);
        LoadBool(root, "Radar", "StaticFlipX", g::radarStaticFlipX);
        LoadColor(root, "Radar", "BgColor", g::radarBgColor);
        LoadColor(root, "Radar", "BorderColor", g::radarBorderColor);
        LoadColor(root, "Radar", "DotColor", g::radarDotColor);
        LoadColor(root, "Radar", "BombColor", g::radarBombColor);
        LoadColor(root, "Radar", "AngleColor", g::radarAngleColor);
        LoadBool(root, "Radar", "SpectatorList", g::radarSpectatorList);
        LoadFloat(root, "Radar", "SpectatorListX", g::radarSpectatorListX);
        LoadFloat(root, "Radar", "SpectatorListY", g::radarSpectatorListY);

        LoadBool(root, "WEBRadar", "Enabled", g::webRadarEnabled);
        LoadInt(root, "WEBRadar", "Port", g::webRadarPort);
        LoadString(root, "WEBRadar", "MapOverride", g::webRadarMapOverride);

        LoadBool(root, "Screen", "VSync", g::vsyncEnabled);
        LoadInt(root, "Screen", "FPSLimit", g::fpsLimit);

        LoadBool(root, "UI", "VisualsPreviewOpen", g::visualsPreviewOpen);
        LoadBool(root, "UI", "RadarCalibrationOpen", g::radarCalibrationOpen);
        LoadBool(root, "UI", "WebRadarQrOpen", g::webRadarQrOpen);
        LoadBool(root, "UI", "WebRadarDebugOpen", g::webRadarDebugOpen);
        LoadInt(root, "UI", "MenuToggleKey", g::menuToggleKey);
